/**
 * A5 printable flyer for hire shops, smoko rooms, supplier counters.
 * URL: /flyer  — Cmd/Ctrl+P → "A5 portrait" → done.
 *
 * QR is generated by api.qrserver.com (free, no API key, no install). The
 * encoded URL includes a UTM parameter so signups from the flyer can be
 * traced in analytics later.
 */
const TARGET_URL = "https://formate.co.nz/?utm_source=flyer&utm_medium=print&utm_campaign=launch";
const QR_URL = `https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=0&data=${encodeURIComponent(TARGET_URL)}`;

export default function Flyer() {
  return (
    <>
      <style>{`
        @page { size: A5 portrait; margin: 0; }
        @media print {
          html, body { background: #fff; }
          .no-print { display: none !important; }
          .flyer { box-shadow: none !important; margin: 0 !important; }
        }
        html, body { margin: 0; padding: 0; }
        body { background: #E5E7EB; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
      `}</style>

      <div className="no-print" style={{ maxWidth: 560, margin: "16px auto", padding: "0 16px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <a href="/" style={{ fontSize: 14, fontWeight: 700, color: "#0F172A", textDecoration: "none" }}>← Back</a>
        <button
          onClick={() => window.print()}
          style={{ background: "#E87722", color: "#fff", fontWeight: 700, padding: "10px 16px", borderRadius: 6, border: 0, cursor: "pointer", fontSize: 14 }}
        >
          Print as A5
        </button>
      </div>

      <div
        className="flyer"
        style={{
          width: "148mm",
          height: "210mm",
          margin: "0 auto",
          background: "linear-gradient(165deg, #0F172A 0%, #1e293b 100%)",
          color: "#fff",
          padding: "16mm 14mm",
          position: "relative",
          overflow: "hidden",
          boxShadow: "0 10px 30px rgba(0,0,0,0.15)",
          fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        }}
      >
        {/* Orange radial accent */}
        <div style={{ position: "absolute", inset: 0, background: "radial-gradient(circle at 80% 10%, rgba(232,119,34,0.35), transparent 50%)", pointerEvents: "none" }} />

        <div style={{ position: "relative", display: "flex", flexDirection: "column", height: "100%" }}>
          {/* Brand */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ width: 10, height: 10, borderRadius: 999, background: "#E87722" }} />
            <div style={{ fontWeight: 900, fontSize: 18, letterSpacing: "-0.01em" }}>
              <span>FOR</span><span style={{ color: "#E87722" }}>MATE</span>
            </div>
          </div>

          {/* Headline */}
          <h1 style={{ fontSize: 44, fontWeight: 900, letterSpacing: "-0.03em", lineHeight: 0.95, marginTop: 30, marginBottom: 0 }}>
            Safety plans<br />in <span style={{ color: "#E87722" }}>60 seconds.</span>
          </h1>

          <p style={{ fontSize: 14, lineHeight: 1.5, color: "rgba(255,255,255,0.7)", marginTop: 18, maxWidth: 280 }}>
            SSSP, SWMS, JSA — all done from your phone, on the ute, before the kettle's boiled.
          </p>

          {/* Bullets */}
          <ul style={{ listStyle: "none", padding: 0, margin: "22px 0 0", fontSize: 13, lineHeight: 1.6 }}>
            {[
              "Fill once. Reuse forever.",
              "Voice input when your hands are dirty.",
              "Email PDF to PCBU 1 — one tap.",
              "WorkSafe NZ &amp; AU WHS compliant.",
            ].map((t, i) => (
              <li key={i} style={{ display: "flex", gap: 8, marginBottom: 6 }}>
                <span style={{ color: "#E87722", fontWeight: 900 }}>✓</span>
                <span dangerouslySetInnerHTML={{ __html: t }} />
              </li>
            ))}
          </ul>

          <div style={{ flex: 1 }} />

          {/* QR + CTA block */}
          <div style={{ display: "flex", alignItems: "flex-end", gap: 16, marginTop: 16 }}>
            <div style={{ background: "#fff", padding: 8, borderRadius: 6, lineHeight: 0 }}>
              <img src={QR_URL} alt="Scan to start free trial" width={120} height={120} style={{ display: "block" }} />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 10, fontWeight: 800, color: "#E87722", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 4 }}>
                30-day free trial
              </div>
              <div style={{ fontSize: 18, fontWeight: 900, letterSpacing: "-0.01em", lineHeight: 1.1, marginBottom: 6 }}>
                Scan to start.
              </div>
              <div style={{ fontSize: 12, color: "rgba(255,255,255,0.55)", fontWeight: 600 }}>
                formate.co.nz
              </div>
              <div style={{ fontSize: 11, color: "rgba(255,255,255,0.4)", marginTop: 4 }}>
                From $19/mo · NZ-made
              </div>
            </div>
          </div>

          {/* Footer */}
          <div style={{ borderTop: "1px solid rgba(255,255,255,0.1)", marginTop: 16, paddingTop: 8, fontSize: 9, color: "rgba(255,255,255,0.3)", textAlign: "center" }}>
            © Afterglow Digital Ltd · Built for NZ &amp; AU tradies
          </div>
        </div>
      </div>
    </>
  );
}
