[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.install.env]
PUPPETEER_SKIP_DOWNLOAD = "true"

[phases.build]
cmds = ["pnpm --filter @workspace/api-server run build"]

[start]
cmd = "node --enable-source-maps ./artifacts/api-server/dist/index.mjs"
