import { Router } from "express";
import { eq, sql, and, isNull } from "drizzle-orm";
import { z } from "zod";
import { db, ssspsTable, pcbuPortalsTable, jsaTable, swmsTable } from "@workspace/db";
import { computeContentHash, recordLockEvent } from "../lib/audit";
import { generateAndStoreSsspSnapshot } from "./sssp-pdf";

const router = Router();

/** Strip private/internal fields before exposing to an unauthenticated viewer or signer. */
function publicShape(s: typeof ssspsTable.$inferSelect) {
  const d = { ...((s.data ?? {}) as Record<string, unknown>) };
  delete d.pcbu1SignToken;
  delete d.pcbu1SignSentTo;
  delete d.pcbu1SignSentAt;
  delete d.shareToken;
  return {
    id: s.id,
    projectName: s.projectName,
    status: s.status,
    data: d,
    createdAt: s.createdAt,
    updatedAt: s.updatedAt,
  };
}

// Public read-only endpoint — no auth required.
// Accessed via the shareable view link sent to PCBU 1 (and others).
// Requires an unguessable shareToken stored in data.shareToken; numeric IDs
// are NOT accepted here to prevent enumeration attacks.
router.get("/sssps/view/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  try {
    const [sssp] = await db.select().from(ssspsTable)
      .where(sql`${ssspsTable.data}->>'shareToken' = ${token}`)
      .limit(1);
    if (!sssp) { res.status(404).json({ error: "Not found" }); return; }
    // Expose the PCBU 1 sign token ONLY while the plan is unsigned, so the viewer
    // can be sent straight to the sign page from the empty signature field. Once
    // PCBU 1 has signed it is withheld again (publicShape always strips it).
    const raw = (sssp.data ?? {}) as Record<string, unknown>;
    const alreadySigned = !!raw.pcbu1SignedBy && !!raw.pcbu1SignedDate;
    const rawSignToken = raw.pcbu1SignToken;
    const signToken = !alreadySigned && typeof rawSignToken === "string" && rawSignToken.length >= 16
      ? rawSignToken
      : undefined;
    res.json({ ...publicShape(sssp), signToken });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch public SSSP by share token");
    res.status(500).json({ error: "Internal server error" });
  }
});

// Token-gated sign-off endpoints. The token lives inside the SSSP's jsonb data
// blob at data.pcbu1SignToken. It's generated by POST /api/sssps/:id/send-for-sign
// and is invalidated once the client signs.

// PCBU sign-off portal — one permanent URL per email address.
// Returns all SSSPs sent to that email so PCBU can track and sign from one place.
router.get("/pcbu/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  try {
    const [portal] = await db.select().from(pcbuPortalsTable)
      .where(eq(pcbuPortalsTable.token, token)).limit(1);
    if (!portal) { res.status(404).json({ error: "Portal not found. Ask your contractor to resend the SSSP." }); return; }

    const sssps = await db.select().from(ssspsTable)
      .where(sql`LOWER(${ssspsTable.data}->>'pcbu1SignSentTo') = ${portal.email.toLowerCase()}`);

    const items = sssps
      .map(s => {
        const d = (s.data ?? {}) as Record<string, unknown>;
        const pcbu2 = (d.pcbu2 ?? {}) as Record<string, string>;
        return {
          id: s.id,
          projectName: s.projectName,
          siteAddress: d.siteAddress as string | undefined,
          pcbu2Company: pcbu2.company,
          pcbu2Contact: pcbu2.contact,
          sentAt: d.pcbu1SignSentAt as string | undefined,
          signedDate: d.pcbu1SignedDate as string | undefined,
          signedBy: d.pcbu1SignedBy as string | undefined,
          signToken: d.pcbu1SignToken as string | undefined,
        };
      })
      .sort((a, b) => {
        // Pending first, then by sent date descending
        const aPending = !a.signedDate ? 0 : 1;
        const bPending = !b.signedDate ? 0 : 1;
        if (aPending !== bPending) return aPending - bPending;
        return (b.sentAt ?? "").localeCompare(a.sentAt ?? "");
      });

    res.json({ email: portal.email, sssps: items });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch PCBU portal");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/sssps/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  try {
    const [sssp] = await db.select().from(ssspsTable)
      .where(sql`${ssspsTable.data}->>'pcbu1SignToken' = ${token}`)
      .limit(1);
    if (!sssp) { res.status(404).json({ error: "This sign-off link is no longer valid. It may have already been used or replaced by a newer one." }); return; }
    // The signer is authorised to read the whole plan, so hand them the shareToken
    // (as viewToken) so they can open & print the full safety-plan document.
    const rawShareToken = ((sssp.data ?? {}) as Record<string, unknown>).shareToken;
    const viewToken = typeof rawShareToken === "string" && rawShareToken.length >= 16 ? rawShareToken : undefined;
    res.json({ ...publicShape(sssp), viewToken });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch SSSP by sign token");
    res.status(500).json({ error: "Internal server error" });
  }
});

const signSchema = z.object({
  signedBy: z.string().trim().min(1).max(200),
  // Optional — typing a name is a valid e-signature; the drawn image is a bonus.
  signatureImage: z.string().min(20).max(2_000_000).optional(), // data:image/png;base64,...
});

router.post("/sssps/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  const parsed = signSchema.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: "Invalid input", details: parsed.error.issues }); return; }
  try {
    const [sssp] = await db.select().from(ssspsTable)
      .where(sql`${ssspsTable.data}->>'pcbu1SignToken' = ${token}`)
      .limit(1);
    if (!sssp) { res.status(404).json({ error: "This sign-off link is no longer valid." }); return; }

    const data = { ...((sssp.data ?? {}) as Record<string, unknown>) };
    // If already signed via this link, treat as idempotent — just return ok.
    if (data.pcbu1SignedBy && data.pcbu1SignedDate) {
      res.json({ ok: true, alreadySigned: true });
      return;
    }
    data.pcbu1SignedBy = parsed.data.signedBy.trim();
    data.pcbu1SignedDate = new Date().toISOString().slice(0, 10);
    if (parsed.data.signatureImage) {
      data.pcbu1SignatureImage = parsed.data.signatureImage;
    } else {
      delete (data as Record<string, unknown>).pcbu1SignatureImage;
    }
    data.pcbu1SignedAt = new Date().toISOString();
    // We keep the token in place so the same link refreshes to a "thanks" view
    // instead of "link no longer valid". A fresh send-for-sign call rotates it.

    await db.update(ssspsTable).set({ data }).where(eq(ssspsTable.id, sssp.id));

    // Freeze-on-sign: auto-lock the SSSP after PCBU1 signs so the final
    // countersigned state becomes the immutable audit record. Idempotent —
    // skipped if already locked. Snapshot is fire-and-forget.
    if (!sssp.lockedAt) {
      const contentHash = computeContentHash(data);
      const [frozen] = await db.update(ssspsTable)
        .set({ lockedAt: new Date(), lockedBy: sssp.userId, snapshotStatus: "pending" })
        .where(and(eq(ssspsTable.id, sssp.id), isNull(ssspsTable.lockedAt)))
        .returning();
      if (frozen) {
        await recordLockEvent({ documentType: "sssp", documentId: sssp.id, actorId: sssp.userId, siteId: sssp.siteId, contentHash }).catch(() => {});
        const rawShareToken = data.shareToken;
        const shareToken = typeof rawShareToken === "string" && rawShareToken.length >= 16 ? rawShareToken : undefined;
        void generateAndStoreSsspSnapshot(sssp.id, { shareToken }, req.log);
      }
    }

    req.log.info({ ssspId: sssp.id, signedBy: data.pcbu1SignedBy }, "PCBU1 signed SSSP via public link");
    res.json({ ok: true });
  } catch (err) {
    req.log.error({ err }, "Failed to record PCBU1 signature");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── JSA public sign-off ─────────────────────────────────────────────────────

router.get("/jsa/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  try {
    const [jsa] = await db.select().from(jsaTable)
      .where(sql`${jsaTable.data}->>'shareToken' = ${token}`)
      .limit(1);
    if (!jsa) { res.status(404).json({ error: "Not found" }); return; }
    const d = { ...((jsa.data ?? {}) as Record<string, unknown>) };
    delete d.shareToken;
    res.json({ id: jsa.id, jobName: jsa.jobName, status: jsa.status, data: d, createdAt: jsa.createdAt });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch public JSA by share token");
    res.status(500).json({ error: "Internal server error" });
  }
});

const jsaSignSchema = z.object({
  signedBy: z.string().trim().min(1).max(200),
  signatureImage: z.string().min(20).max(2_000_000).optional(),
});

router.post("/jsa/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  const parsed = jsaSignSchema.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: "Invalid input" }); return; }
  try {
    const [jsa] = await db.select().from(jsaTable)
      .where(sql`${jsaTable.data}->>'shareToken' = ${token}`)
      .limit(1);
    if (!jsa) { res.status(404).json({ error: "Link no longer valid." }); return; }
    const data = { ...((jsa.data ?? {}) as Record<string, unknown>) };
    if (data.principalSignedBy && data.principalSignedDate) {
      res.json({ ok: true, alreadySigned: true }); return;
    }
    data.principalSignedBy = parsed.data.signedBy.trim();
    data.principalSignedDate = new Date().toISOString().slice(0, 10);
    data.principalSignedAt = new Date().toISOString();
    if (parsed.data.signatureImage) data.principalSignatureImage = parsed.data.signatureImage;
    await db.update(jsaTable).set({ data }).where(eq(jsaTable.id, jsa.id));
    req.log.info({ jsaId: jsa.id, signedBy: data.principalSignedBy }, "Principal signed JSA via public link");
    res.json({ ok: true });
  } catch (err) {
    req.log.error({ err }, "Failed to record JSA principal signature");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── SWMS public sign-off ─────────────────────────────────────────────────────

router.get("/swms/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  try {
    const [swms] = await db.select().from(swmsTable)
      .where(sql`${swmsTable.data}->>'shareToken' = ${token}`)
      .limit(1);
    if (!swms) { res.status(404).json({ error: "Not found" }); return; }
    const d = { ...((swms.data ?? {}) as Record<string, unknown>) };
    delete d.shareToken;
    res.json({ id: swms.id, activityName: swms.activityName, status: swms.status, data: d, createdAt: swms.createdAt });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch public SWMS by share token");
    res.status(500).json({ error: "Internal server error" });
  }
});

const swmsSignSchema = z.object({
  signedBy: z.string().trim().min(1).max(200),
  signatureImage: z.string().min(20).max(2_000_000).optional(),
});

router.post("/swms/sign/:token", async (req, res) => {
  const token = String(req.params.token ?? "");
  if (!token || token.length < 16) { res.status(400).json({ error: "Invalid token" }); return; }
  const parsed = swmsSignSchema.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: "Invalid input" }); return; }
  try {
    const [swms] = await db.select().from(swmsTable)
      .where(sql`${swmsTable.data}->>'shareToken' = ${token}`)
      .limit(1);
    if (!swms) { res.status(404).json({ error: "Link no longer valid." }); return; }
    const data = { ...((swms.data ?? {}) as Record<string, unknown>) };
    if (data.principalSignedBy && data.principalSignedDate) {
      res.json({ ok: true, alreadySigned: true }); return;
    }
    data.principalSignedBy = parsed.data.signedBy.trim();
    data.principalSignedDate = new Date().toISOString().slice(0, 10);
    data.principalSignedAt = new Date().toISOString();
    if (parsed.data.signatureImage) data.principalSignatureImage = parsed.data.signatureImage;
    await db.update(swmsTable).set({ data }).where(eq(swmsTable.id, swms.id));
    req.log.info({ swmsId: swms.id, signedBy: data.principalSignedBy }, "Principal signed SWMS via public link");
    res.json({ ok: true });
  } catch (err) {
    req.log.error({ err }, "Failed to record SWMS principal signature");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
